### ISSUE TITLE
希望增加自动纠错的支持 Spelling correction support wanted

### ISSUE THREAD

**Issue by Youxikong** [qzly/RimeControl#1]
Rime 0.13.0开始支持自动纠错。
[feat: spelling correction](https://github.com/rime/librime/pull/228)
设置translator/enable_correction为true就能使用自动纠错。

**Comment by qzly** [comment]
ok，我先看看

**Comment by qzly** [comment]
需要在输入方案上修改，需要些时间

**Comment by thisistianqi** [comment]
RimeControlv20190307闪退，没有报错，直接闪退。win10，1803，64位，兼容模式也闪退。

**Comment by Youxikong** [comment]
> RimeControlv20190307闪退，没有报错，直接闪退。win10，1803，64位，兼容模式也闪退。

为什么不另开一个issue呢。。

**Comment by qzly** [comment]
@Youxikong 我刚刚更新了一个版本，初步完成自动纠错的支持。你测试下是否满足要求。（PS：不好意思，拖了这么久）

**Comment by Youxikong** [comment]
> @Youxikong 我刚刚更新了一个版本，初步完成自动纠错的支持。你测试下是否满足要求。（PS：不好意思，拖了这么久）

Perfect!
完美。
